import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const urbanist = Urbanist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Happier Studio",
  description: "Generated by ochoagram",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es"
    //className="bg-slate-900 text-slate-100"
    >
      <head>
        <title>Happier Studio ッ</title>
        <link rel="icon" href="./favicon.ico" />
      </head>
      <body className={urbanist.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
