import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const urbanist = Urbanist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Happiier Studio",
  description: "Generated by ochoagram",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es"
    //className="bg-slate-900 text-slate-100"
    >
      <head>
        <title>Happiier Studio ッ</title>
        <link rel="icon" href="./favicon.ico" />
      </head>
      <body className={urbanist.className}>
        <Header />
        {children}
        {/* <div className="background-gradient absolute inset-0 -z-50 max-h-screen" />
        <div className="pointer-events-none absolute inset-0 -z-40 h-full bg-[url('/noisetexture.jpg')] opacity-5 mix-blend-soft-light"></div> */}
        <Footer />
      </body>
    </html>
  );
}
