// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  equipo: dynamic(() => import("./Equipo")),
  hero: dynamic(() => import("./Hero")),
};
