// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blog_post_index: dynamic(() => import("./ContentIndex")),
  contact_links: dynamic(() => import("./ContactLinks")),
  equipo: dynamic(() => import("./Equipo")),
  hero: dynamic(() => import("./Hero")),
  image: dynamic(() => import("./Image")),
  image_block: dynamic(() => import("./ImageBlock")),
  image_gallery: dynamic(() => import("./ImageGallery")),
  main_only_text: dynamic(() => import("./MainOnlyText")),
  project: dynamic(() => import("./Project")),
  service_list: dynamic(() => import("./ServiceList")),
  services: dynamic(() => import("./Services")),
  text_block: dynamic(() => import("./TextBlock")),
};
