// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blog_post_index: dynamic(() => import("./ContentIndex")),
  equipo: dynamic(() => import("./Equipo")),
  hero: dynamic(() => import("./Hero")),
  image_block: dynamic(() => import("./Image")),
  main_only_text: dynamic(() => import("./MainOnlyText")),
  services: dynamic(() => import("./Services")),
  text_block: dynamic(() => import("./TextBlock")),
};
